### ISSUE TITLE
Cannot install AG on Windows with Python 3.8 due to ConfigSpace

### ISSUE THREAD

**Issue by AnthonyTheKoala** [awslabs/autogluon#683]
I am having having problems installing ConfigSpace by whatever means, whether it is. Whether it is installing directly by pipping configspace or by pipping autogluon, no matter how ConfigSpace is installed, I get the same error message whether I am installing configspace by installing autogluon or by installing it directly by pipping configspace.

<pre>
C:\Python38>pip install ConfigSpace --upgrade --force --no-color
Collecting ConfigSpace
  Using cached ConfigSpace-0.4.15.tar.gz (964 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python38\python.exe' 'c:\python38\lib\site-packages\pip' install
 --ignore-installed --no-user --prefix 'C:\Users\A\AppData\Local\Temp\pip-build-
env-c1vor2mj\overlay' --no-warn-script-location --no-binary :none: --only-binary
 :none: -i https://pypi.org/simple -- setuptools wheel numpy Cython
       cwd: None
  Complete output (42 lines):
  Traceback (most recent call last):
    File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\python38\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "c:\python38\lib\site-packages\pip\__main__.py", line 26, in <module>
      sys.exit(_main())
    File "c:\python38\lib\site-packages\pip\_internal\cli\main.py", line 73, in
main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "c:\python38\lib\site-packages\pip\_internal\commands\__init__.py", lin
e 104, in create_command
      module = importlib.import_module(module_path)
    File "c:\python38\lib\importlib\__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

    File "c:\python38\lib\site-packages\pip\_internal\commands\install.py", line
 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup

    File "c:\python38\lib\site-packages\pip\_internal\cli\req_command.py", line
16, in <module>
      from pip._internal.index.collector import LinkCollector
    File "c:\python38\lib\site-packages\pip\_internal\index\collector.py", line
14, in <module>
      from pip._vendor import html5lib, requests
    File "c:\python38\lib\site-packages\pip\_vendor\requests\__init__.py", line
125, in <module>
      from . import utils
    File "c:\python38\lib\site-packages\pip\_vendor\requests\utils.py", line 25,
 in <module>
      from . import certs
    File "c:\python38\lib\site-packages\pip\_vendor\requests\certs.py", line 15,
 in <module>
      from pip._vendor.certifi import where
    File "c:\python38\lib\site-packages\pip\_vendor\certifi\__init__.py", line 1
, in <module>
      from .core import contents, where
    File "c:\python38\lib\site-packages\pip\_vendor\certifi\core.py", line 12, i
n <module>
      from importlib.resources import path as get_path, read_text
    File "c:\python38\lib\importlib\resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401

    File "c:\python38\lib\site-packages\typing.py", line 1359, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "c:\python38\lib\site-packages\typing.py", line 1007, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python38\python.exe' 'c:\pyth
on38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Us
ers\A\AppData\Local\Temp\pip-build-env-c1vor2mj\overlay' --no-warn-script-locati
on --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setupto
ols wheel numpy Cython Check the logs for full command output.
</pre>

* "Check the logs for full command output" - where are they and what is their name please? I tried searching for *.log, log*.* to no avail.

* Are there any other things I must do?

Info:
OS: Win 7 - 64-bit
mysys64: mingw64, version 10.2.2
MSVC: CL version Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24234.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
Python: v3.8.5 64-bit
numpy.__version__: '1.19.2'
cython.__version__: '0.29.21'
pyparsing.__version__:'2.4.7'

So if I am installing autogluon which uses configspace or trying to install configspace, are there any actions to do?
I tried the path environment. 

Many thanks,
Anthony of Sydney

**Comment by Innixma** [comment]
Hi Anthony,

Thanks for the detailed bug report!

Could you try installing via python 3.7? Python 3.8 is currently not officially supported by AutoGluon: #120. Users have commented that AutoGluon version 0.0.13 is installable on Windows via Python 3.7.3 : #164 

If it is critical for you to work in Python 3.8, I'd recommend opening an issue in the configspace GitHub, as it appears your problem is not AutoGluon specific but is tied directly to configspace.

**Comment by Innixma** [comment]
I have added a 'help wanted' label to this issue to encourage anyone that runs into similar issues to comment regarding any work-arounds or solutions they have found. Ideally we want to add Python 3.8 support in future and solving this issue will be important in that regard.

**Comment by AnthonyTheKoala** [comment]
I am cutting a long story very short.
While it applies to ConfigSpace, this package is relevant to the installation of autogluon which uses ConfigSpace.
NOW this  is about the installation of ConfigSpace.
* downgraded pip to 18.1 in order to avoid the PEP 517 problem
<pre>
pip install --user pip==18.1
</pre>
This is a long story cut short.
* My python version is 3,8.5 - I have invested a lot of bandwidth (downloads) in downloading packages to 3.8.5.
* I have added the package line_profiler #So much to explain the reasoning of installing this.
<pre>
pip install line_profiler
</pre>
* I have installed MS Visual Studio 2019, not just the visual tools. 2019. 
* The cygwincompiler.py had to be modified to accomodate versions of MS Visual Studio > MSVC 12
<pre>
def get_msvcr():
	# Using appropriate MS compiler
	# Adapted from https://bugs.python.org/file40608/patch.diff
  
	msc_pos = sys.version.find('MSC v.')
	
	if msc_pos != -1:
		msc_ver = sys.version[msc_pos+6:msc_pos+10]
		if msc_ver == '1600':
			return ['msvcr100']
		elif msc_ver >= '1900':
			# Visual Studio 2015 / Visual C++ 14.0
            # "msvcr140.dll no longer exists" http://blogs.msdn.com/b/vcblog/archive/2014/06/03/visual-studio-14-ctp.aspx
			return['msvcp140']; #try 'vcruntime140' or 'msvcp140'
		else:
			raise ValueError("Unknown MS Compiler version %s " % msc_ver)
</pre>
* Note for the above I did the above for another package pystan. I am avoiding anaconda and miniconda and tried to install from source - enough said. That is irrelevant for this.
* I had to modify the environment variable PATH to include amongst other packages c:\msys64\mingw64\bin and for python38's package - c:\users\whatever\AppData\Roaming\Python\Scripts.
* In other words if you thought the python38 environment variables path was c:\python38\scripts (say), for some inexplicable reason, you will find that the scripts which is also in c:\python38\scripts is also installed at c:\users\whatever\AppData\Roaming\Python\scripts and any compilation attempt may 'spew' if you don't include this additional path environment **EVEN IF ** you have installed in the path c:\python38\scripts.
<pre>
C:\Users\whatever\AppData\Roaming\Python\Scripts;C:\Windows\System32\WindowsPowerShell\v1.0;C:\swigwin-4.0.2;%mscvc_2019%\bin\Hostx64\x64;%msvc_2019%\include;%msvc_2019%\lib\x64 ;C:\msys64\mingw64\bin;C:\msys64\mingw64\include;C:\msys64\mingw64\lib;c:\python38;c:\python38\scripts;c:\python38\DLLs;c:\python38\Lib;c:\python38\libs;c:\python38\libs\python38.lib;;%graphviz_home%;%java_bin%;%java_include%;C:\windows\system32;c:\windows; 
</pre>
So far so good.
You may ask why install MSVC 2019/Visual Studio 2019? 
Good question! When you boot up the IDLE package, you will see the MSVC version that the Python 3.8.6 was compiled.
<pre>
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32
</pre>
MS Visual Studio 2019's says MSVC v1927 and that is what you need as a C compiler.
* In addition you will want to install the the msvc runtimes by
<pre>
pip install --user msvc_runtime 
</pre>
* Note if you open the *.whl file using 7-zip (open as archive), you'll find that they are the *.dll files used in the MSVC runtime. _These *.dll files match the version of the MSVC 1927_
* **BUT** not all msvc runtime dll files are the same even if they are v 1927! DON'T REPLACE THE DLL FILES FROM THE MSVC redistributables, otherwise your installation of whatever package will 'spew' out errors.  So don't install that in the c:\python38 and c:\python38\scripts. USE THE dll files automatically installed from pipping the msvc_runtime.

Anyway, having said all that, you are on the way of installing ConfigSpace, BUT FOR a little thing.
<pre>
File "C:\Users\A\AppData\Local\Temp\pip-install-gi442ns7\numpy\numpy\distutils\mingw32ccompiler.py", line 564, in msvc_manifest_xml
          raise ValueError("Version %d,%d of MSVCRT not supported yet" %
      ValueError: Version 14,1 of MSVCRT not supported yet
</pre>
The important line is:
<pre>
      ValueError: Version 14,1 of MSVCRT not supported yet
</pre>
Conclusion , I will be patient and wait until ConfigSpace, a component of AutoGluon is updated to handle the latest MSVC 2019.

Thank you,
Anthony of Sydney

**Comment by Innixma** [comment]
Hi Anthony,

Thanks for the detailed bug report. We have taken note of it and will reference it when we expand AutoGluon support to Python 3.8.

Best,
Nick

**Comment by Innixma** [comment]
Please consider trying this again on pre-release or after v0.1 releases. We believe that the majority of issues related to ConfigSpace have been resolved, but have not tested this on Windows. Please re-open if issues persist.
